CREATE DATABASE IF NOT EXISTS ftp_pda;

USE ftp_pda;

CREATE TABLE IF NOT EXISTS demonstracoes_contabeis (
    DATA DATE,
    REG_ANS CHAR(6),
    CD_CONTA_CONTABIL VARCHAR(255),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15, 2),
    VL_SALDO_FINAL DECIMAL(15, 2)
);

CREATE TABLE IF NOT EXISTS relatorio_cadop (
    REG_ANS CHAR(6),
    CNPJ VARCHAR(18),
    RAZAO_SOCIAL VARCHAR(255),
    NOME_FANTASIA VARCHAR(255),
    MODALIDADE VARCHAR(255),
    LOGRADOURO VARCHAR(255),
    NUMERO VARCHAR(255),
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255),
    CIDADE VARCHAR(255),
    UF CHAR(2),
    CEP VARCHAR(255),
    DDD CHAR(2),
    TELEFONE VARCHAR(255),
    FAX VARCHAR(255),
    ENDERECO_ELETRONICO VARCHAR(255),
    REPRESENTANTE VARCHAR(255),
    CARGO_REPRESENTANTE VARCHAR(255),
    REGIAO_COMERCIALIZACAO CHAR(1),
    DATA_REG_ANS DATE
)